budget_tracker/budget/urls.py
from django.urls import path
from . import views


app_name = "budget"


urlpatterns = [
    path("expenses/", views.ExpenseListView.as_view(), name="expense-list"),
    path("expense/add/", views.ExpenseAddView.as_view(), name="expense-add"),
    path("expense/<pk>/update/", views.ExpenseUpdateView.as_view(), name="expense-update"),
    path("expense/<pk>/delete/", views.ExpenseDeleteView.as_view(), name="expense-delete"),
    path("income/", views.IncomeListView.as_view(), name="income-list"),
    path("income/add/", views.IncomeAddView.as_view(), name="income-add"),
    path("income/<pk>/update/", views.IncomeUpdateView.as_view(), name="income-update"),
    path("income/<pk>/delete/", views.IncomeDeleteView.as_view(), name="income-delete"),
    path("goals/", views.GoalListView.as_view(), name="goal-list"),
    path("goal/<pk>", views.GoalDetailView.as_view(), name="goal-detail"),
    path("goal/add/", views.GoalAddView.as_view(), name="goal-add"),
    path("goal/<pk>/update/", views.GoalUpdateView.as_view(), name="goal-update"),
    path("goal/<pk>/delete/", views.GoalDeleteView.as_view(), name="goal-delete"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("", views.HomeView.as_view(), name="home")
]

budget_tracker/budget_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("budget.urls"))
]

budget_tracker/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/icon.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">

    <title>
        {% block title  %}
            undefined title
        {% endblock title  %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    {% block head %}{% endblock head %}
    
    <style>
        body {
            background-color: whitesmoke; !important
        }
    </style>

</head>
<body>

    <nav aria-label="Primary" class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="container-fluid">

            <a class="navbar-brand" href="{% url 'budget:home' %}">
                <img src="{% static 'img/icon.png' %}" alt="logo" width="30" height="30">
                <span>Budget Tracker</span>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'budget:expense-list' %}">Expenses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'budget:income-list' %}">Income</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'budget:goal-list' %}">Goals</a>
                    </li>

                </ul>

            </div>

            <span class="d-flex me-4">
                <a href="{% url 'budget:settings' %}" class="nav-item text-light">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                        <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
                    </svg>
                </a>
            </span>

        </div>
    </nav>

    <div class="container pt-4">
        {% if messages %}
            {% for message in messages %}
                <div class="container mt-3">
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                </div>
            {% endfor %}
        {% endif %}


        {% block content %}{% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    {% block script %}{% endblock script %}
</body>
</html>